sudo: false

language: java
jdk:
  - oraclejdk8
env:
  global:
    - secure: "VU18XfDamnTAME+JoHHmBNI2mo63VpStrmHS4qWDjHM5rVWfwa1u1U+nGor65DHDFqck8In/ILRzXOwVzLsZc4aV/IJGtQS9wSxE+tEBUCQS0ud/KFYCF2aCXAOwJsaSW7dCl/IBhdqooYy2FIs3LNhIZp6r6TEcNunQzLfjTF0cUsiAc/qC+GbFEwOpPLvilJUucJ3uqjGJhySi5phJTcc7vryX8wpFcqGXoSx1Z7GbU0PxHZiIO/tlewx1jm9gz4x6UoGs8yjcrRrbqMs3jGbvYf88alWV2MSUvS+yjR2Ult5mSBCRYU+6TFQo7QDJduz64+E/FW2k0ETqkRlVuTSw+c/TIDFOUtFbtMm5ViSHU9vjHfhoteQ8DgeVXlOmQgyfo4bGAM/1+YSPvlcPI2Z3ah7Ddk+brblGWhrXvL9+/fAcFryCr8zfjvENAJs+5urjr/9AJoThjICDjweHTjK+Y/lwTAmWIhICp6yj0kq49h/qRWL7aPOq06j8//GobnDb+JeXoChTGlhg83peW/5p045nDRKwS1hJjLG4sDCQcV38E8fff5gtDpyhHxu1Z9JRP1EmTNYFYajahBGl7+KarBhsRfpxYf0fMAqx78nWZ5dN3ohwlq2sXIxwGEWxEHoVumOWpkhBCqwE3GsF+lBbHAXk8PEHs7zGoUAqHhg="
cache:
  directories:
    - $HOME/.m2
  
script: 
  - "mvn cobertura:cobertura"
  - "mvn javadoc:javadoc"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash Deploy_JavaDoc.sh

notification:
  email:
    on_success: never
    on_failure: always
